name: notes
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  retrofit: ^4.0.1
  auto_route: ^7.7.1
  sliver_tools: ^0.2.12
  sizer: ^2.0.15
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4
  firebase_auth: ^4.7.2
  uuid: ^3.0.7
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.7
  flutter_staggered_grid_view: ^0.7.0
  package_info_plus: ^4.0.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true

flutter_gen:
  integrations:
    flutter_svg: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  auto_route_generator: ^7.2.0
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
