// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3k4hCfc_woXehhM9fr5tdNNdzjgBomyg',
    appId: '1:122302560628:web:a71526a8bd244a6c2c5421',
    messagingSenderId: '122302560628',
    projectId: 'note-73ace',
    authDomain: 'note-73ace.firebaseapp.com',
    storageBucket: 'note-73ace.appspot.com',
    measurementId: 'G-7LXVLQV11N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV8Sx3xabivHkc1aJyGRmLGoq-CpWvdq4',
    appId: '1:122302560628:android:1f46b6d8907b57282c5421',
    messagingSenderId: '122302560628',
    projectId: 'note-73ace',
    storageBucket: 'note-73ace.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAutz-Zyqo0xrcCClyquZnMSYzq5p83rbc',
    appId: '1:122302560628:ios:ebddb1963c137a9c2c5421',
    messagingSenderId: '122302560628',
    projectId: 'note-73ace',
    storageBucket: 'note-73ace.appspot.com',
    iosClientId: '122302560628-i26ljamcoijo30p6kpli7lgq0mfs6r91.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAutz-Zyqo0xrcCClyquZnMSYzq5p83rbc',
    appId: '1:122302560628:ios:4a93e6e7f9df2bb82c5421',
    messagingSenderId: '122302560628',
    projectId: 'note-73ace',
    storageBucket: 'note-73ace.appspot.com',
    iosClientId: '122302560628-107h4c1mvaqqfp2u6ue5np6ta5s8m1ia.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes.RunnerTests',
  );
}
